# Generated by Django 5.0.4 on 2026-03-26 17:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('couleur', models.CharField(default='#6b6860', help_text="Code couleur hexadécimal pour l'interface", max_length=7, verbose_name='Couleur')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
                'unique_together': {('entreprise', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Contact')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('pays', models.CharField(default='Sénégal', max_length=50, verbose_name='Pays')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('reference', models.CharField(max_length=100, verbose_name='Référence')),
                ('code_barre', models.CharField(blank=True, max_length=100, verbose_name='Code barre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('modele_compatible', models.CharField(blank=True, help_text='Ex: Toyota Corolla 2010-2020, Peugeot 206', max_length=200, verbose_name='Modèle(s) compatible(s)')),
                ('prix_achat', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Prix d'achat (FCFA)")),
                ('prix_vente', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix de vente (FCFA)')),
                ('quantite_stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité en stock')),
                ('seuil_alerte', models.IntegerField(default=5, help_text='Déclenche une alerte quand le stock descend sous ce seuil', verbose_name="Seuil d'alerte")),
                ('emplacement', models.CharField(blank=True, help_text='Ex: Rayon A3, Étagère 2', max_length=50, verbose_name='Emplacement')),
                ('unite', models.CharField(default='Pièce', max_length=20, verbose_name='Unité')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Photo')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='stock.categorie', verbose_name='Catégorie')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.entreprise', verbose_name='Entreprise')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='stock.fournisseur', verbose_name='Fournisseur principal')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement inventaire'), ('retour', 'Retour fournisseur'), ('perte', 'Perte / casse')], max_length=20, verbose_name='Type')),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('quantite_avant', models.IntegerField(default=0, verbose_name='Qté avant mouvement')),
                ('quantite_apres', models.IntegerField(default=0, verbose_name='Qté après mouvement')),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Prix unitaire (FCFA)')),
                ('reference_document', models.CharField(blank=True, help_text='N° de facture, bon de commande, etc.', max_length=100, verbose_name='Référence document')),
                ('motif', models.TextField(blank=True, verbose_name='Motif / remarque')),
                ('date_mouvement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_crees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.entreprise', verbose_name='Entreprise')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.fournisseur', verbose_name='Fournisseur (si entrée)')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['entreprise', 'reference'], name='stock_produ_entrepr_9da78a_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['entreprise', 'categorie'], name='stock_produ_entrepr_5c9b68_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['entreprise', 'quantite_stock'], name='stock_produ_entrepr_a5b68f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('entreprise', 'reference')},
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['entreprise', 'produit', '-date_mouvement'], name='stock_mouve_entrepr_ae7244_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['entreprise', 'type_mouvement', '-date_mouvement'], name='stock_mouve_entrepr_7d3435_idx'),
        ),
    ]
