# Generated by Django 5.0.4 on 2026-04-12 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/photos/', verbose_name='Photo')),
                ('legende', models.CharField(blank=True, help_text='Ex: Vue avant, Référence gravée', max_length=100, verbose_name='Légende')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Photo produit',
                'verbose_name_plural': 'Photos produit',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
