# Generated by Django 6.0.3 on 2026-04-13 14:59

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_add_produit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.validators.CheminUploadSecurise('produits'), validators=[apps.common.validators.valider_image], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='produitphoto',
            name='image',
            field=models.ImageField(upload_to=apps.common.validators.CheminUploadSecurise('produits/photos'), validators=[apps.common.validators.valider_image], verbose_name='Photo'),
        ),
    ]
