# Generated by Django 6.0.3 on 2026-04-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_produit_image_alter_produitphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie'), ('ajustement', 'Ajustement inventaire'), ('retour_fournisseur', 'Retour fournisseur'), ('retour_client', 'Retour client'), ('perte', 'Perte / casse')], max_length=20, verbose_name='Type'),
        ),
    ]
