# Generated by Django 5.0.4 on 2026-05-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_mouvementstock_type_mouvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='reference_equivalente',
            field=models.CharField(blank=True, help_text="Références équivalentes d'autres marques (ex: ATE 24.0120, LPR BK1030)", max_length=200, verbose_name='Réf. équivalente / cross-ref'),
        ),
        migrations.AddField(
            model_name='produit',
            name='reference_oem',
            field=models.CharField(blank=True, help_text='Référence constructeur officielle (ex: 3C0 615 301 D)', max_length=100, verbose_name='Référence OEM'),
        ),
        migrations.AddField(
            model_name='produit',
            name='type_vehicule',
            field=models.CharField(blank=True, choices=[('PL', 'Poids Lourd'), ('VL', 'Véhicule Léger'), ('TOUS', 'PL & VL')], default='TOUS', max_length=4, verbose_name='Type de véhicule'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='modele_compatible',
            field=models.CharField(blank=True, help_text='Ex: Renault Trucks T, Mercedes Actros, Peugeot Partner', max_length=200, verbose_name='Modèle(s) compatible(s)'),
        ),
    ]
