# Generated by Django 5.0.4 on 2026-05-21 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_produit_champs_automobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibiliteVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('modele', models.CharField(blank=True, max_length=200, verbose_name='Modèle')),
                ('annee_debut', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année début')),
                ('annee_fin', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année fin')),
                ('carburant', models.CharField(choices=[('tous', 'Tous carburants'), ('diesel', 'Diesel'), ('essence', 'Essence'), ('gnv', 'GNV / GNC'), ('hybride', 'Hybride'), ('electrique', 'Électrique'), ('gpl', 'GPL')], default='tous', max_length=20, verbose_name='Carburant')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilites', to='stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Compatibilité véhicule',
                'verbose_name_plural': 'Compatibilités véhicules',
                'ordering': ['marque', 'modele', 'annee_debut'],
            },
        ),
    ]
