# Generated by Django 5.0.4 on 2026-06-05 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_compatibilite_vehicule'),
        ('tenants', '0002_alter_entreprise_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='compatibilitevehicule',
            index=models.Index(fields=['produit', 'marque'], name='stock_compa_produit_1af0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='compatibilitevehicule',
            index=models.Index(fields=['marque', 'modele'], name='stock_compa_marque_41521e_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['entreprise', 'reference_document'], name='stock_mouve_entrepr_18dd48_idx'),
        ),
    ]
