# Generated by Django 5.0.4 on 2026-03-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('slug', models.SlugField(unique=True, verbose_name='Identifiant unique')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, help_text='Utilisé sur les factures (recommandé : 300x100px, PNG)', null=True, upload_to='logos/', verbose_name='Logo')),
                ('ninea', models.CharField(blank=True, help_text="Numéro d'Identification National des Entreprises et Associations", max_length=50, verbose_name='NINEA')),
                ('registre_commerce', models.CharField(blank=True, max_length=50, verbose_name='Registre du commerce')),
                ('devise', models.CharField(default='FCFA', max_length=10, verbose_name='Devise')),
                ('tva_taux', models.DecimalField(decimal_places=2, default=18.0, help_text='Taux de TVA applicable au Sénégal : 18%', max_digits=5, verbose_name='Taux TVA (%)')),
                ('mentions_facture', models.TextField(blank=True, help_text='Texte affiché en bas de chaque facture', verbose_name='Mentions légales facture')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['nom'],
            },
        ),
    ]
