# Generated by Django 6.0.3 on 2026-04-13 14:59

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, help_text='Utilisé sur les factures (recommandé : 300x100px, PNG)', null=True, upload_to=apps.common.validators.CheminUploadSecurise('logos'), validators=[apps.common.validators.valider_image], verbose_name='Logo'),
        ),
    ]
