# Generated by Django 6.0.3 on 2026-04-13 14:59

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.validators.CheminUploadSecurise('avatars'), validators=[apps.common.validators.valider_image], verbose_name='Avatar'),
        ),
    ]
