# Generated by Django 5.0.4 on 2026-03-26 17:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom / Raison sociale')),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise / Garage'), ('revendeur', 'Revendeur')], default='entreprise', max_length=20, verbose_name='Type')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Nom du contact')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('telephone2', models.CharField(blank=True, max_length=20, verbose_name='Téléphone 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, default='Dakar', max_length=100, verbose_name='Ville')),
                ('ninea', models.CharField(blank=True, max_length=50, verbose_name='NINEA')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('date_emission', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('montant_ht', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Montant HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_tva', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Montant TVA')),
                ('remise_globale', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise globale (%)')),
                ('montant_ttc', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Montant TTC')),
                ('montant_paye', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='Montant payé')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('partielle', 'Partiellement payée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money'), ('credit', 'Crédit (paiement différé)')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Conditions')),
                ('objet', models.CharField(blank=True, max_length=200, verbose_name='Objet')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='facturation.client', verbose_name='Client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='Copie du nom produit — modifiable manuellement', max_length=200, verbose_name='Désignation')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('quantite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix unitaire HT')),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture', verbose_name='Facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_facture', to='stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Montant (FCFA)')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('free_money', 'Free Money'), ('credit', 'Crédit (paiement différé)')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, help_text='N° de chèque, référence Wave, etc.', max_length=100, verbose_name='Référence')),
                ('date_paiement', models.DateField(default=django.utils.timezone.now, verbose_name='Date de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.entreprise', verbose_name='Entreprise')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='facturation.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['entreprise', 'statut', '-date_emission'], name='facturation_entrepr_51f7b5_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['entreprise', 'client', '-date_emission'], name='facturation_entrepr_97311a_idx'),
        ),
    ]
