# Generated by Django 5.0.4 on 2026-04-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Numéro de facture'),
        ),
        migrations.AlterUniqueTogether(
            name='facture',
            unique_together={('entreprise', 'numero')},
        ),
    ]
