# Generated by Django 5.0.4 on 2026-06-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_add_soft_delete_facture'),
        ('tenants', '0002_alter_entreprise_logo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['entreprise', 'nom'], name='facturation_entrepr_3dece7_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['entreprise', 'actif'], name='facturation_entrepr_d9a7d5_idx'),
        ),
    ]
